# Generated by Django 5.0.6 on 2025-01-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayentry',
            old_name='content',
            new_name='content_left',
        ),
        migrations.AddField(
            model_name='dayentry',
            name='content_right',
            field=models.TextField(blank=True),
        ),
    ]
